#!/bin/bash

# Runs pip-compile on the current platform and generates the shared
# requirements.txt
# pip-compile can be obtained via `pip3 install pip-tools`
# On ubuntu, I need it for both python3 and python3.7 (for colab)

# I can use these to build bionic/focal:
# docker run -i -t -v $(pwd):/root/mount -w /root/mount robotlocomotion/drake:bionic
# docker run -i -t -v $(pwd):/root/mount -w /root/mount robotlocomotion/drake:focal
# We also need
# export LC_ALL=C.UTF-8 LANG=C.UTF-8; apt update && apt install -y lsb-release python3-pip python3.7 python3-venv; pip3 install --upgrade pip-tools build; python3.7 -m pip install pip-tools
# (Note: running from mac docker crashes if torch is included; it
# works when docker is run from bionic. go figure)
#
# For making a distribution
# (https://packaging.python.org/en/latest/tutorials/packaging-projects/)
# python3 -m build
# Then from *outside* of docker, run
# python3 -m twine upload dist/*
set -euo pipefail

if [[ "${OSTYPE}" == "darwin"* ]]; then
    pip-compile mac-requirements.in
elif [[ "$(lsb_release -cs)" == 'focal' ]]; then
    # TODO: Add setup.cfg (as below) once we support pip install drake on focal
    python3 -m piptools compile -v focal-requirements.in
else
    # Bring in colab requirements:
    # First update colab_pip_freeze.txt via
    # a) running `node colab_pip_freeze.js` in the htmlbook directory, or
    # b) manually running "!pip3 freeze" in colab and copying the result.
    #
    # Then make some local modifications:
    # - Fix scipy version, because manipulation/exercises/rl:policy_gradient
    #   hit a scipy/numpy mismatch bug.
    # - googlecolab version is a lie
    # - Remove bespoke torch download versions
    # - cloudpickle1.3.0 can't parse files saved by cloudpickle1.6.0
    # - matplotlib version from colab doesn't work with bazel
    #    https://github.com/RobotLocomotion/drake/issues/14250
    # - traitlets==5.05 requires python3.7
    # - kiwisolver==1.3.2 requires python3.7
    # - scikit-learn>=1.0.0 requires python3.7
    # - colab's install is inconsistent (and makes warnings for my pip)
    #   albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll #   have imgaug 0.2.9 which is incompatible.

    cat htmlbook/colab-pip-freeze.txt | sed \
        -e 's/^scipy.*/scipy==1.5.3/' \
        -e 's/^google-colab.*/git+git:\/\/github.com\/googlecolab\/colabtools\/\#egg=google-colab/' \
        -re 's/^.*(torch[a-z]*-[\.0-9]+).*/\1/' \
        -e 's/^cloudpickle==/cloudpickle>=/' \
        -e '/^matplotlib/d' \
        -e '/^traitlets/d' \
        -e '/^kiwisolver.*/d' \
        -e '/^scikit-learn/d' \
        > htmlbook/colab-constraints-ubuntu.txt

    python3 -m piptools compile bionic-requirements.in setup.cfg --output-file=bionic-requirements.txt

    cat htmlbook/colab-pip-freeze.txt | sed \
        -e 's/^scipy.*/scipy==1.5.3/' \
        -e 's/^google-colab.*/git+git:\/\/github.com\/googlecolab\/colabtools\/\#egg=google-colab/' \
        -e '/+cu111.*/d' \
        -e 's/^cloudpickle==/cloudpickle>=/' \
        -e '/^imgaug/d' \
        > htmlbook/colab-constraints-colab.txt

    python3.7 -m piptools compile colab-requirements.in setup.cfg --output-file=colab-requirements.txt

    echo ""
    echo "IMPORTANT: Don't forget to test these requirements using"
    echo "https://colab.research.google.com/drive/19mv-nL0Klga__lu_DD0njq9QktvfyKBh"
fi

echo "# This file is auto-generated by htmlbook/requirements.sh" > requirements.txt
cat mac-requirements.txt |  sed -e '/#/d' -e '/^$/d' -e 's/$/ ; sys_platform == "darwin"/' >> requirements.txt
cat bionic-requirements.txt | sed -e '/#/d' -e '/^$/d' -e 's/$/; sys_platform == "linux" and python_version < "3.8" /' >> requirements.txt
cat focal-requirements.txt | sed -e '/#/d' -e '/^$/d' -e 's/$/; sys_platform == "linux" and python_version >= "3.8" /' >> requirements.txt
