#!/bin/bash

# Runs pip-compile on the current platform and generates the shared
# requirements.txt
# pip-compile can be obtained via `pip3 install pip-tools`

set -euo pipefail

if [[ "${OSTYPE}" == "darwin"* ]]; then
    pip-compile mac-requirements.in
else
    pip-compile ubuntu-requirements.in
    pip-compile colab-requirements.in
fi

echo "# This file is auto-generated by htmlbook/requirements.sh" > requirements.txt
cat mac-requirements.txt |  sed -e '/#/d' -e '/^$/d' -e 's/$/ ; sys_platform == "darwin"/' >> requirements.txt
cat ubuntu-requirements.txt | sed -e '/#/d' -e '/^$/d' -e 's/$/; sys_platform == "linux"/' >> requirements.txt
