#!/bin/zsh

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

# Check that GitHub Actions is running the workflow that calls this script.
# https://docs.github.com/en/actions/reference/environment-variables
if [[ "${GITHUB_ACTIONS:-}" !=  "true" ]]; then
  echo "This script is only intended to be run on Github actions"
  exit 1
fi

echo "GITHUB_ACTIONS="$GITHUB_ACTIONS

# Pass the --retry 4 argument when invoking curl(1).
export HOMEBREW_CURL_RETRIES=4

# Do not send brew(1) usage analytics to Google Analytics.
export HOMEBREW_NO_ANALYTICS=1

# Do not automatically update before running various brew(1) subcommands.
export HOMEBREW_NO_AUTO_UPDATE=1

# Fail on the failure of installation from a bottle rather than falling back to
# building from source.
# TODO(jamiesnape): Since https://github.com/Homebrew/brew/pull/10640 this is
# the default so this probably can be removed.
export HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=1

# Forbid redirects from secure HTTPS to insecure HTTP.
export HOMEBREW_NO_INSECURE_REDIRECT=1

# Never automatically cleanup installed, upgraded, and/or reinstalled formulae.
export HOMEBREW_NO_INSTALL_CLEANUP=1

# brew update uses git(1), so HOMEBREW_CURL_RETRIES does not take effect.
rm -f /usr/local/bin/go
rm -f /usr/local/bin/gofmt

brew update || (sleep 30; brew update)

# The bazelisk formula conflicts with the bazel formula.
# https://github.com/actions/virtual-environments/issues/1365
# https://github.com/Homebrew/homebrew-core/blob/7250542ee8545a4545daad294c0c5fb92a13d224/Formula/bazelisk.rb#L18
brew uninstall -f -q bazelisk
#brew unlink node@18

# conda has caused trouble in the past.
sudo rm -rf /usr/local/bin/conda /usr/local/miniconda
rm -rf "${HOME}/.conda"

# Remove the symlinks that cause issues.
find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
sudo rm -rf /Library/Frameworks/Python.framework/
find /usr/local/bin -lname '*/Library/Frameworks/Python3.framework/*' -delete
sudo rm -rf /Library/Frameworks/Python3.framework/

brew untap homebrew/cask || true
brew untap homebrew/core || true

# Run upgrades now to fail-fast (setup scripts do this anyway).
brew update && brew upgrade

BREW_PYTHON_DIR="/opt/homebrew/opt/python@3.12"
# Attempting to create missing symlinks..."
ln -sf $BREW_PYTHON_DIR/bin/python3.12 $BREW_PYTHON_DIR/bin/python3
ln -sf $BREW_PYTHON_DIR/bin/pip3.12 $BREW_PYTHON_DIR/bin/pip3
export PATH="/opt/homebrew/opt/python@3.12/bin:$PATH"

# brew doctor || true

./setup/mac/install_prereqs.sh
if [[ $(python3 --version) != "Python 3.12"* ]]; then
    echo "ERROR: Failed to use Homebrew Python 3.12"
    exit 1
fi
trap 'brew cleanup && rm -rf "$(brew --cache)"' EXIT

# We need nbconvert outside of the virtual environment to install the templates.
pip3 install --break-system-packages nbconvert
ln -s /opt/homebrew/share/jupyter/ ~/Library/Jupyter

# Pre-fetch the pip dependencies.
bazel fetch //...
