#!/bin/zsh

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

echo "GITHUB_ACTIONS="$GITHUB_ACTIONS

# Pass the --retry 4 argument when invoking curl(1).
export HOMEBREW_CURL_RETRIES=4

# Do not send brew(1) usage analytics to Google Analytics.
export HOMEBREW_NO_ANALYTICS=1

# Do not automatically update before running various brew(1) subcommands.
export HOMEBREW_NO_AUTO_UPDATE=1

# Fail on the failure of installation from a bottle rather than falling back to
# building from source.
# TODO(jamiesnape): Since https://github.com/Homebrew/brew/pull/10640 this is
# the default so this probably can be removed.
export HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=1

# Forbid redirects from secure HTTPS to insecure HTTP.
export HOMEBREW_NO_INSECURE_REDIRECT=1

# Never automatically cleanup installed, upgraded, and/or reinstalled formulae.
export HOMEBREW_NO_INSTALL_CLEANUP=1

# Only list updates to installed formulae.
export HOMEBREW_UPDATE_REPORT_ONLY_INSTALLED=1

# brew update uses git(1), so HOMEBREW_CURL_RETRIES does not take effect.
rm -f /usr/local/bin/go
rm -f /usr/local/bin/gofmt
brew update || (sleep 30; brew update)

# Check that GitHub Actions is running the workflow that calls this script.
# https://docs.github.com/en/actions/reference/environment-variables
if [[ "${GITHUB_ACTIONS:-}" ==  "true" ]]; then
  # The bazelisk formula conflicts with the bazel formula.
  # https://github.com/actions/virtual-environments/issues/1365
  # https://github.com/Homebrew/homebrew-core/blob/7250542ee8545a4545daad294c0c5fb92a13d224/Formula/bazelisk.rb#L18
  brew uninstall -f -q bazelisk
  brew unlink tcl-tk

  # conda has caused trouble in the past.
  sudo rm -rf /usr/local/bin/conda /usr/local/miniconda
  rm -rf "${HOME}/.conda"

  # Remove the symlinks that cause issues.
  find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
  sudo rm -rf /Library/Frameworks/Python.framework/

  # Run upgrades now to fail-fast (setup scripts do this anyway).
  brew update && brew upgrade

  # On 2023-02-16 the pip3.11 symlink was mysteriously missing.
  brew unlink python@3.11 && brew link python@3.11
  pip3.11 --version
fi

./setup/mac/install_prereqs.sh
trap 'brew cleanup && rm -rf "$(brew --cache)"' EXIT

pushd /tmp
curl -LsSO -m 60 --retry 4 --retry-delay 0 https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac.tar.gz
popd
trap 'brew cleanup && rm -rf /tmp/drake-latest-mac.tar.gz "$(brew --cache)"' EXIT
pushd /opt
sudo tar -xf /tmp/drake-latest-mac.tar.gz
popd

/opt/drake/share/drake/setup/install_prereqs --without-update

# This version should match mac-requirements.txt
pip3.11 install --upgrade matplotlib==3.7.0
