#!/bin/bash

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euo pipefail

# Run the tests in batches to reduce the memory footprint on CI. (I was running
# out of memory on manipulation's jammy CI)
bazel query 'kind(test, //...)' > /tmp/my_tests.txt
sed 's#^//:#:#g' /tmp/my_tests.txt > /tmp/all_tests.txt

BATCH_SIZE=10
TOTAL_LINES=$(wc -l < /tmp/all_tests.txt)
START_LINE=1

while [ $START_LINE -lt $TOTAL_LINES ]; do
    echo "Running tests from $START_LINE to $((START_LINE + BATCH_SIZE)) of $TOTAL_LINES"
    # Get batch of test targets
    TESTS=$(sed -n "$START_LINE,+$BATCH_SIZE p" /tmp/all_tests.txt)
    
    # Run tests for the batch
    # Run via xvfb to enable headless rendering.
    xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset' \
      bazel test --cache_test_results=no --discard_analysis_cache=yes \
        --jobs=2 --keep_going=yes --keep_state_after_build=no \
        --repository_cache= --test_output=errors \
        --test_verbose_timeout_warnings=yes \
        --track_incremental_state=no --verbose_failures=no \
        --test_env=GITHUB_ACTIONS --test_env=DRAKE_RESOURCE_ROOT \
        --test_env=MANIPULATION_DATA_DIR --test_env=UNDERACTUATED_DATA_DIR \
        --verbose_test_summary=no $TESTS

    # Clean up
    bazel clean

    # Move to the next batch
    START_LINE=$((START_LINE + BATCH_SIZE))
done
