#!/bin/zsh

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

export HOMEBREW_NO_ANALYTICS=1 HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK=1

rm -f /usr/local/bin/2to3 # Temporary fix
brew unlink gcc@8 gcc@9 # Temporary fix
./scripts/setup/mac/install_prereqs.sh
trap 'brew cleanup && rm -rf "$(brew --cache)"' EXIT

pushd /tmp
curl -LsSO -m 60 --retry 4 --retry-delay 0 https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-mac.tar.gz
popd
trap 'brew cleanup && rm -rf /tmp/drake-latest-mac.tar.gz "$(brew --cache)"' EXIT
pushd /opt
sudo tar -xf /tmp/drake-latest-mac.tar.gz
popd

export HOMEBREW_CURL_RETRIES=4

rm -f /usr/local/bin/2to3 # Temporary fix

/opt/drake/share/drake/setup/install_prereqs
