#!/bin/bash

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 DEBIAN_FRONTEND=noninteractive

./scripts/setup/ubuntu/18.04/install_prereqs.sh
trap 'rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/*' EXIT

LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 pip3 install --disable-pip-version-check --upgrade --requirement ./requirements.txt

pushd /opt
wget -nv https://drake-packages.csail.mit.edu/drake/continuous/drake-latest-bionic.tar.gz
trap 'rm -rf /opt/drake-latest-bionic.tar.gz /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/*' EXIT
tar -xf drake-latest-bionic.tar.gz
popd

apt-get install -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy --no-install-recommends $(cat /opt/drake/share/drake/setup/packages-bionic.txt)

# Setup xvfb for headless rendering.
apt-get install -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy --no-install-recommends xvfb

cat << EOF > /lib/systemd/system/xvfb.service
[Unit]
After=network.target
[Service]
ExecStart=/usr/bin/Xvfb :99 -screen 0 1280x1024x24 -ac +extension GLX +extension RANDR +render -noreset
[Install]
WantedBy=multi-user.target
EOF

/bin/systemctl --now --quiet enable /lib/systemd/system/xvfb.service
