#!/bin/bash

# Copyright 2020 Massachusetts Institute of Technology.
# Licensed under the BSD 3-Clause License. See LICENSE.TXT for details.

set -euxo pipefail

export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 DEBIAN_FRONTEND=noninteractive

./setup/ubuntu/20.04/install_prereqs.sh
trap 'rm -rf /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/*' EXIT

# I don't need this because bazel will download the requirements:
#LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 pip3 install --disable-pip-version-check --upgrade --requirement ./requirements.txt

pushd /opt
wget -nv https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-focal.tar.gz
trap 'rm -rf /opt/drake-latest-focal.tar.gz /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin /var/lib/apt/lists/* /var/log/apt/*' EXIT
tar -xf drake-latest-focal.tar.gz
popd

apt-get install -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy --no-install-recommends $(cat /opt/drake/share/drake/setup/packages-focal.txt)

# Setup xvfb for headless rendering.
apt-get install -o APT::Acquire::Retries=4 -o Dpkg::Use-Pty=0 -qy --no-install-recommends xvfb

# Pre-fetch data so that no one test needs to fetch it
PYTHONPATH=/opt/drake/lib/python3.8/site-packages python3 -c \
    'from pydrake.all import PackageMap; PackageMap().GetPath("drake_models")'
