---
name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'

jobs:
  mac:
    name: macos catalina 10.15
    runs-on: macos-10.15
    steps:
      - name: check free space before
        run: df -h
        shell: zsh -efuo pipefail {0}
      - name: checkout
        uses: actions/checkout@v2
      - name: install brew prerequisites
        run: ./setup/mac/install_prereqs
        shell: bash
      - name: install pip prerequisites
        run: ./setup/mac/install_pip_prereqs
        shell: zsh -efuo pipefail {0}
      - name: check free space after
        run: df -h
        shell: zsh -efuo pipefail {0}

  ubuntu:
    name: ubuntu 18.04 bionic beaver
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - name: check free space before
        run: df -h
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: install apt prerequisites
        run: ./setup/ubuntu/install_prereqs
        shell: bash
      - name: install pip prerequisites
        run: ./setup/ubuntu/install_pip_prereqs
        shell: bash
      - name: check free space after
        run: df -h
        shell: bash
